package com.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TestCourse {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testCourse() {
        driver.get("http://inginformatica.uniroma2.it/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.linkText("Corsi")).click();
        driver.findElement(By.cssSelector(".simple-table:nth-child(28) tr:nth-child(6) > td:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector(".simple-table:nth-child(28) tr:nth-child(6) > td:nth-child(2)")).getText(), is("Davide Falessi"));
    }
}
