// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSeleniumGUITest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSeleniumGUI() {
    driver.get("https://didatticaweb.uniroma2.it/it/home/accedi/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector(".nav-item:nth-child(5) .title")).click();
    driver.findElement(By.id("input")).click();
    driver.findElement(By.id("input")).sendKeys("Falessi");
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".even:nth-child(5) a")).click();
    driver.findElement(By.cssSelector(".page-title > span")).click();
    driver.findElement(By.cssSelector(".page-title")).click();
    driver.findElement(By.cssSelector(".page-title > span")).click();
    driver.findElement(By.cssSelector(".page-title")).click();
    assertThat(driver.findElement(By.cssSelector(".page-title > span")).getText(), is("Ingegneria Del Software E Progettazione Web"));
  }
}
